    var config1 = liquidFillGaugeDefaultSettings();
    config1.circleColor = jun.v1_color[0];
    config1.textColor = jun.v1_color[1];
    config1.waveTextColor = jun.v1_color[2];
    config1.waveColor = jun.v1_color[0];
    config1.circleThickness = 0.2;
    config1.textVertPosition = 0.5;
    config1.waveAnimateTime = 2000;
    config1.waveHeight = 0.1;

    var config2 = liquidFillGaugeDefaultSettings();
    config2.circleColor = jun.v2_color[0];
    config2.textColor = jun.v2_color[1];
    config2.waveTextColor = jun.v2_color[2];
    config2.waveColor = jun.v2_color[0];
    config2.circleThickness = 0.2;
    config2.textVertPosition = 0.5;
    config2.waveAnimateTime = 2000;
    config2.waveHeight = 0.1;